## Progetto ML 2023/2024 - lettura dati

In [113]:
import pandas as pd
import os
import numpy as np
import math
google_reviews_data = pd.read_csv(os.path.join('.', "google_review_ratings.csv"))

In [114]:
google_reviews_data

,User,Category 1,Category 2,Category 3,Category 4,Category 5,Category 6,Category 7,Category 8,Category 9,...,Category 14,Category 15,Category 16,Category 17,Category 18,Category 19,Category 20,Category 21,Category 22,Category 23
0,User 1,0.00,0.00,3.63,3.65,5.00,2.92,5.00,2.35,2.33,...,1.72,1.74,0.59,0.50,0.00,0.50,0.00,0.00,0.0,0.0
1,User 2,0.00,0.00,3.63,3.65,5.00,2.92,5.00,2.64,2.33,...,1.72,1.74,0.59,0.50,0.00,0.50,0.00,0.00,0.0,0.0
2,User 3,0.00,0.00,3.63,3.63,5.00,2.92,5.00,2.64,2.33,...,1.72,1.74,0.59,0.50,0.00,0.50,0.00,0.00,0.0,0.0
3,User 4,0.00,0.50,3.63,3.63,5.00,2.92,5.00,2.35,2.33,...,1.72,1.74,0.59,0.50,0.00,0.50,0.00,0.00,0.0,0.0
4,User 5,0.00,0.00,3.63,3.63,5.00,2.92,5.00,2.64,2.33,...,1.72,1.74,0.59,0.50,0.00,0.50,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5450,User 5451,0.91,3.94,3.98,2.78,2.76,2.57,2.44,1.11,1.78,...,1.31,1.33,0.67,0.66,0.67,1.59,5.00,1.04,5.0,5.0
5451,User 5452,0.91,5.00,4.00,2.79,2.77,2.57,2.43,1.09,1.77,...,1.29,5.00,0.66,0.65,0.66,0.69,5.00,1.05,5.0,5.0
5452,User 5453,0.93,5.00,4.02,2.79,2.78,2.57,1.77,1.07,1.76,...,1.27,0.89,0.65,0.64,0.65,1.59,1.62,1.06,5.0,5.0
5453,User 5454,0.94,5.00,4.03,2.80,2.78,2.57,1.75,1.05,1.75,...,1.25,0.87,0.65,0.63,0.64,0.74,5.00,1.07,5.0,5.0
5454,User 5455,0.95,4.05,4.05,2.81,2.79,2.44,1.76,1.03,1.74,...,1.23,5.00,0.64,0.63,0.64,0.75,5.00,1.08,5.0,5.0

In [115]:
split_size = np.shape(google_reviews_data)[0]
split_limit = split_size - math.floor(split_size * 0.25)
split_limit

4092

In [116]:
google_reviews_data_training = google_reviews_data[google_reviews_data.index < split_limit]
google_reviews_data_test = google_reviews_data[google_reviews_data.index >= split_limit]

In [117]:
google_reviews_data = google_reviews_data.dropna(axis='columns')
google_reviews_data_training = google_reviews_data_training.dropna(axis='columns')
google_reviews_data_test = google_reviews_data_test.dropna(axis='columns')

In [118]:
#google_reviews_data = google_reviews_data[:-1]
#google_reviews_data_training = google_reviews_data_training[:-1]
#google_reviews_data_test = google_reviews_data_test[:-1]

In [119]:
google_reviews_data

,User,Category 1,Category 2,Category 3,Category 4,Category 5,Category 6,Category 7,Category 8,Category 9,...,Category 14,Category 15,Category 16,Category 17,Category 18,Category 19,Category 20,Category 21,Category 22,Category 23
0,User 1,0.00,0.00,3.63,3.65,5.00,2.92,5.00,2.35,2.33,...,1.72,1.74,0.59,0.50,0.00,0.50,0.00,0.00,0.0,0.0
1,User 2,0.00,0.00,3.63,3.65,5.00,2.92,5.00,2.64,2.33,...,1.72,1.74,0.59,0.50,0.00,0.50,0.00,0.00,0.0,0.0
2,User 3,0.00,0.00,3.63,3.63,5.00,2.92,5.00,2.64,2.33,...,1.72,1.74,0.59,0.50,0.00,0.50,0.00,0.00,0.0,0.0
3,User 4,0.00,0.50,3.63,3.63,5.00,2.92,5.00,2.35,2.33,...,1.72,1.74,0.59,0.50,0.00,0.50,0.00,0.00,0.0,0.0
4,User 5,0.00,0.00,3.63,3.63,5.00,2.92,5.00,2.64,2.33,...,1.72,1.74,0.59,0.50,0.00,0.50,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5450,User 5451,0.91,3.94,3.98,2.78,2.76,2.57,2.44,1.11,1.78,...,1.31,1.33,0.67,0.66,0.67,1.59,5.00,1.04,5.0,5.0
5451,User 5452,0.91,5.00,4.00,2.79,2.77,2.57,2.43,1.09,1.77,...,1.29,5.00,0.66,0.65,0.66,0.69,5.00,1.05,5.0,5.0
5452,User 5453,0.93,5.00,4.02,2.79,2.78,2.57,1.77,1.07,1.76,...,1.27,0.89,0.65,0.64,0.65,1.59,1.62,1.06,5.0,5.0
5453,User 5454,0.94,5.00,4.03,2.80,2.78,2.57,1.75,1.05,1.75,...,1.25,0.87,0.65,0.63,0.64,0.74,5.00,1.07,5.0,5.0
5454,User 5455,0.95,4.05,4.05,2.81,2.79,2.44,1.76,1.03,1.74,...,1.23,5.00,0.64,0.63,0.64,0.75,5.00,1.08,5.0,5.0

In [120]:
google_reviews_data.to_csv('google_review_ratings.csv', ',', index=False)
google_reviews_data_test.to_csv('test.csv', ',', index=False)
google_reviews_data_training.to_csv('training.csv', ',', index=False)